Update FileSharePasswordView
jamf/JamfSync pull request #40
Opened 2024-10-29 15:29 UTC by BIG-RAT

Display the read/write account when prompting for the password of a file share.

2024-10-29 16:44 UTC, HarryStrandJamf requested changes

2024-10-29 16:44 UTC, HarryStrandJamf commented on JamfSync/UI/FileSharePasswordView.swift
> +                       .frame(width: 420, height: 30, alignment: .leading)
It's best to avoid frames altogether if you can, but if not, then just specify the parts of the frame that you really need (like height maybe).

2024-10-29 16:44 UTC, HarryStrandJamf commented on JamfSync/UI/FileSharePasswordView.swift
> +                           .frame(width: 420, height: 30, alignment: .leading)
It's best to avoid frames altogether if you can, but if not, then just specify the parts of the frame that you really need (like height maybe).

2024-10-29 16:44 UTC, HarryStrandJamf commented on JamfSync/UI/FileSharePasswordView.swift
> +                   .textCase(nil)
nil is the default, so this can be removed.

2024-10-29 16:44 UTC, HarryStrandJamf commented on JamfSync/UI/FileSharePasswordView.swift
> +                        .padding(EdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0))
Is this necessary? I would think removing this padding call would have the same results.

2024-10-29 16:44 UTC, HarryStrandJamf commented on JamfSync/UI/FileSharePasswordView.swift
> +                    Section(header: Text("Password:")  // Label
The horizontal spacing is messed up around this.

2024-11-22 19:41 UTC, rydgecrakerjamf commented on JamfSync/UI/FileSharePasswordView.swift
> +                    .padding(EdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0))
And if it is necessary, can you achieve the same thing by just calling .padding(0) so you don't have to create the new object each time it's redrawn?

2025-01-29 16:25 UTC, HarryStrandJamf approved these changes

2025-01-29 16:44 UTC, HarryStrandJamf requested changes
After looking at this more, I don't know if this whole change makes sense or not. The username is stored in Jamf Pro, so if it changes, it will be changed back again the next time data is loaded. So if the username is incorrect, it should be corrected in Jamf Pro and not here.

2025-01-30 03:20 UTC, HarryStrandJamf commented
After talking with Leslie about the purpose of this, he said it was because there were folks having issues because they had/wanted individual accounts set up to access the share. Perhaps because of auditing requirements. We decided to make it work as follows: It starts by looking for a keychain entry for the username provided by Jamf Pro, and if that fails, then it checks to see if there is a username saved in the user defaults, and if so, then it will look for a keychain entry there. If so, then it loads and all is well. Otherwise, it will display the dialog along with whatever username it tried last. Once it successfully mounts the file share, then it saves the last username used to the user defaults. So next time it shouldn’t require that the password is entered.

2025-01-30 05:18 UTC, BIG-RAT reviewed
looks good

2025-01-30 17:41 UTC, HarryStrandJamf approved these changes

2025-01-30 17:41 UTC, merged